vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.o.scrolloff = 8
vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.nu = true
vim.opt.relativenumber = true
